GET http://localhost:8888/messages/all
content-type: application/json

###

POST http://localhost:8888/messages/all
content-type: application/json

{
  "channel": "private-my-channel",
  "type": "not-important"
}

###

DELETE http://localhost:8888/messages/delete/6603102c815eab3d4695c546
content-type: application/json

###

POST http://localhost:8888/messages/new
content-type: application/json

{
  "author": "Sistema",
  "type": "important",
  "date": "03-18-2024",
  "text": "Essa é uma mensagem do sistema. Mostrar ela na tela",
  "channel": "private-my-channel"
}

###

POST http://localhost:8888/logs
content-type: application/json

{
  "name": "teste"
}

###

GET http://localhost:8888/logs/all
content-type: application/json

###