GET http://localhost:8888/messages
content-type: application/json

###

GET http://localhost:8888/messages/all/private-my-channel
content-type: application/json

###

GET http://localhost:8888/messages/message/123
content-type: application/json

###

POST http://localhost:8888/messages/new HTTP/1.1
content-type: application/json

{
  "author": "Rafael",
  "text": "Recado salvo no banco",
  "type": "not-important",
  "channel": "private-my-channel"
}

###

DELETE http://localhost:8888/messages/delete/65f85998ec674aa1c903db7b
content-type: application/json

###

POST http://localhost:8888/pusher/auth HTTP/1.1
content-type: application/json

{
  "socket_id": "Rafael",
  "channel_name": "private-my-channel"
}

###

POST http://localhost:8888/new-message HTTP/1.1
content-type: application/json

{
  "author": "Sistema",
  "type": "important",
  "date": "03-18-2024",
  "text": "Essa é uma mensagem do sistema. Mostrar ela na tela",
  "channel": "private-my-channel"
}

###

GET http://localhost:8888/messages/all
content-type: application/json

{
  "type": "not-important",
  "channel": "private-meu-mural"
}